version: '3.7'
services:
  sadtalker:
    build: .
    container_name: sadtalker
    
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./results:/home/SadTalker/results
    ports:
      - 10364:10364
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - TTS_SERVER=http://tts:9566/tts
    command: uvicorn main:app --reload --port 10364 --host 0.0.0.0
  
